services:

  db:
    image: postgres:14.5
    container_name: educa-db
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file: .env

  cache:
    image: redis:7.0.4
    container_name: educa-cache
    restart: always
    volumes:
      - ./data/cache:/data

  web:
    build: .
    container_name: educa-web
    command:
      [
        "python",
        "/code/manage.py",
        "runserver",
        "0.0.0.0:8000"
      ]
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=educa.settings.prod
    depends_on:
      - db
      - cache
    env_file: .env
